import assert from 'node:assert/strict';
import {getYieldPoolEvidence,getYieldTool,compareYieldTool,getYieldHistoryTool,compareYieldHistoryTool} from '../packages/shared/defillama/research';
import {getAcrossRoutes,getAcrossFeeQuote,intentDepositAcross} from '../packages/shared/across/bridge';
import {decodeFunctionData,erc20Abi} from 'viem';
import {acrossSpokePoolAbi} from '../packages/shared/across/constants';
let requests:string[]=[];
let pools:any[]=[{pool:'rh-pool',chain:'Robinhood Chain',project:'ekubo',symbol:'ETH-USDG',apy:4000,apyBase:null,apyReward:4000,tvlUsd:11000,apyPct1D:null,predictions:{predictedClass:null,predictedProbability:null}}, {pool:'eth-pool',chain:'Ethereum',project:'aave-v3',symbol:'USDC',apy:3,tvlUsd:10000000,stablecoin:true}];
let responseStatus=200, malformedFee=false, allowance=0n, decimals=18, native=false, noRoutes=false;
const owner='0x1111111111111111111111111111111111111111',token='0x2222222222222222222222222222222222222222',other='0x3333333333333333333333333333333333333333';
globalThis.fetch=async(input:any)=> {
 const url=String(input);requests.push(url);
 if(responseStatus!==200)return new Response('{}',{status:responseStatus});
 let data:any;
 if(url.includes('/available-routes')) data=noRoutes?[]:[{originChainId:1,destinationChainId:8453,originToken:token,destinationToken:other,originTokenSymbol:'WETH',destinationTokenSymbol:'WETH',isNative:native}];
 else if(url.includes('/suggested-fees')) data={totalRelayFee:malformedFee?undefined:{total:'100'},timestamp:Math.floor(Date.now()/1000),exclusiveRelayer:owner,exclusivityDeadline:0};
 else if(url.includes('/chart/')) data={data:[{timestamp:new Date(Date.now()-86400000).toISOString(),apy:10,tvlUsd:10},{timestamp:new Date().toISOString(),apy:null,tvlUsd:null}]};
 else data={data:pools};
 return new Response(JSON.stringify(data),{status:200});
};
const client:any={getAddress:async()=>owner,getPublicClient:()=>({getBlock:async()=>({number:10n,hash:'0x'+'a'.repeat(64)}),getBytecode:async()=>'0x6000',readContract:async({functionName}:any)=>functionName==='decimals'?decimals:allowance}),getWalletClient:()=>{throw Error('Must never obtain signing authority')},executeOps:()=>{throw Error('Must never execute')}};
const call=async(tool:any,args:any)=>tool.execute(client,tool.parameters.parse(args));
let result=await call(getYieldTool,{chainId:4663});assert.equal(result.yields.length,1);assert.equal(result.yields[0].chainId,4663);assert.equal(result.yields[0].trend['1d'],null);assert.equal(result.yields[0].prediction.confidence,null);assert.equal(result.yields[0].risk,'unverified');assert.ok(result.observedAt);
assert.equal((await call(getYieldTool,{chain:'Robinhood'})).yields[0].pool,'rh-pool');
let before=requests.length;await assert.rejects(()=>call(getYieldTool,{chain:'Ethereum',chainId:4663}),/Conflicting/);assert.equal(requests.length,before);
assert.equal((await call(getYieldTool,{chainId:4663,protocol:'Aave'})).count,0);
assert.equal((await call(compareYieldTool,{chainId:4663,assets:['ETH']})).comparisons[0].yields[0].chainId,4663);
assert.equal((await call(getYieldHistoryTool,{chainId:4663,poolId:'rh-pool'})).missingApyPoints,1);
await assert.rejects(()=>call(getYieldHistoryTool,{chainId:1,poolId:'rh-pool'}),/network/);
const partial=await call(compareYieldHistoryTool,{chainId:4663,poolIds:['rh-pool','missing']});assert.equal(partial.complete,false);assert.equal(partial.errors.length,1);
responseStatus=503;await assert.rejects(()=>call(getYieldTool,{chainId:4663}));await assert.rejects(()=>call(getAcrossRoutes,{originChainId:1,destinationChainId:8453}),/unknown/);responseStatus=200;
const args={originChainId:1,destinationChainId:8453,inputToken:token,outputToken:other,recipient:owner,amount:'1',isNative:false};
let proposal=await call(intentDepositAcross,args);assert.equal(proposal.ops.length,2);assert.equal(proposal.hash,undefined);
let approval=decodeFunctionData({abi:erc20Abi,data:proposal.ops[0].data});assert.equal(approval.args![1],10n**18n);
let deposit=decodeFunctionData({abi:acrossSpokePoolAbi,data:proposal.ops[1].data});assert.equal(deposit.args![5],10n**18n-100n);
allowance=1n;proposal=await call(intentDepositAcross,args);assert.equal(proposal.ops.length,3);assert.equal(decodeFunctionData({abi:erc20Abi,data:proposal.ops[0].data}).args![1],0n);
native=true;proposal=await call(intentDepositAcross,{...args,isNative:true});assert.equal(proposal.ops.length,1);assert.equal(proposal.ops[0].value,'1000000000000000000');
malformedFee=true;await assert.rejects(()=>call(getAcrossFeeQuote,{...args,isNative:true}),/fee/);malformedFee=false;
noRoutes=true;assert.equal((await call(getAcrossRoutes,args)).routes.length,0);await assert.rejects(()=>call(getAcrossFeeQuote,args),/No live/);noRoutes=false;
await assert.rejects(()=>call(intentDepositAcross,{...args,recipient:other}),/same wallet/);
await assert.rejects(()=>call(getAcrossFeeQuote,{...args,isNative:true,amount:'0.0000000000000000001'}),/precision/);
await assert.rejects(()=>call(getAcrossFeeQuote,{...args,originChainId:4663}),/deployment/);
pools[0].underlyingTokens=[token,'invalid'];
const evidence=await call(getYieldPoolEvidence,{chainId:4663,poolId:'rh-pool'});assert.equal(evidence.project,'ekubo');assert.equal(evidence.complete,false);assert.equal(evidence.tokenChecks[0].codePresent,true);assert.equal(evidence.poolContractVerified,false);
console.log('Yield and Across shared-source offline fixtures passed; no network or signing.');
